### PR TITLE
Add dialog window to ask user if opening of a new tab is blocked by browser

### PR DESCRIPTION
**Pull request by mmorhun**
Signed-off-by: Mykola Morhun <mmorhun@redhat.com>

This PR adds functionality which shows dialog window to user if browser policy denies opening of a new tabs. 
hosted-instance-dialog2

Fixes https://github.com/eclipse/che/issues/9644

### CODE REVIEW

**Comment by benoitf** [comment]
should we display the link that we want to open ?

**Comment by evidolob** [comment]
I agree with @benoitf, we should display the link

**Comment by mmorhun** [comment]
Ok, I'll add hosted instance link

**Comment by mmorhun** [comment]
@evidolob @benoitf I updated code and screenshot

**Review by benoitf — APPROVED** [review]

**Comment by olexii4** [comment]
@mmorhun  Do you really want to merge 35 commits into master?

**Review by olexii4 — APPROVED** [review]

**Review by evidolob — APPROVED** [review]

**Pull request merged**
